preserve_hierarchy: true

files:
  - source: 'sources/15w14a/en_US.lang'
    dest: '15w14a.lang'
    translation: /resources/15w14a/assets/minecraft/lang/%locale%.lang

  - source: 'sources/1.RV-Pre1/en_us.lang'
    dest: '1.RV-Pre1.lang'
    translation: /resources/1.RV-Pre1/assets/minecraft/lang/%locale_with_underscore%.lang

  - source: 'sources/3D_Shareware_v1.34/en_us.json'
    dest: '3D_Shareware_v1.34.json'
    translation: /resources/3D_Shareware_v1.34/assets/minecraft/lang/%locale_with_underscore%.json

  - source: 'sources/20w14infinite/en_us.json'
    dest: '20w14infinite.json'
    translation: /resources/20w14infinite/assets/minecraft/lang/%locale_with_underscore%.json

  - source: 'sources/22w13oneBlockAtATime/en_us.json'
    dest: '22w13oneBlockAtATime.json'
    translation: /resources/22w13oneBlockAtATime/assets/minecraft/lang/%locale_with_underscore%.json

  - source: 'sources/23w13a_or_b/en_us.json'
    dest: '23w13a_or_b.json'
    translation: /resources/23w13a_or_b/assets/minecraft/lang/%locale_with_underscore%.json

  - source: 'sources/24w14potato/en_us.json'
    dest: '24w14potato.json'
    translation: /resources/24w14potato/assets/minecraft/lang/%locale_with_underscore%.json

  - source: 'sources/25w14craftmine/en_us.json'
    dest: '25w14craftmine.json'
    translation: /resources/25w14craftmine/assets/minecraft/lang/%locale_with_underscore%.json