name: Upload Releases

on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'Release channel'
        required: true
        type: choice
        default: beta
        options:
          - release
          - beta
          - alpha
      name:
        description: 'Version name'
        required: false
        type: string
      changes:
        description: 'Change notes (JSON string)'
        required: false
        type: string
  schedule:
    - cron: '0 18 * 1-3,5-12 0'
    - cron: '0 18 2-7,9,12,15,20,25,30 4 *'

jobs:
  sync_and_prepare:
    runs-on: ubuntu-latest
    outputs:
      has_commits: ${{ steps.check.outputs.has_commits }}
      recent_logs: ${{ steps.check.outputs.recent_logs }}
      channel: ${{ steps.check.outputs.channel }}
      folders_json: ${{ steps.list_folders.outputs.folders_json }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check recent commits
        id: check
        run: |
          DATE=1.week.ago
          DAY=$(date +%-d)
          CHANNEL=release
          if [[ $(date +%-m) == 4 ]]; then
            DATE=5.days.ago
            if [[ $DAY -lt 13 ]]; then
              DATE=3.days.ago
            fi
            if [[ $DAY -lt 8 ]]; then
              DATE=1.day.ago
              if [[ $DAY -lt 7 ]]; then
                CHANNEL=beta
              fi
            fi
            if [[ $DAY -lt 4 ]]; then
              if [[ $DAY == 2 ]]; then
                DATE=1.week.ago
              fi
              CHANNEL=alpha
            fi
          fi
          git log --since=$DATE --stat --oneline --no-decorate > recent_logs.txt
          sed -i ':a;N;$!ba;s/\n/<br>\n/g' recent_logs.txt
          RECENT_LOGS=$(sed ':a;N;$!ba;s/\( deletions\?(-)<br>\n\)/\1\n/g' recent_logs.txt)
          echo "Recent logs: $(cat recent_logs.txt)"
          if [[ $RECENT_LOGS =~ /lang/ ]]; then
            echo "has_commits=true" >> $GITHUB_OUTPUT
          else
            echo "has_commits=false" >> $GITHUB_OUTPUT
          fi
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)  # To define the separator
          echo "recent_logs<<EOF"$'\n'"$RECENT_LOGS"$'\n'EOF >> $GITHUB_OUTPUT  # For the multi-line output
          echo "channel=$CHANNEL" >> $GITHUB_OUTPUT

      - name: List folders
        id: list_folders
        run: |
          FOLDERS=$(find ./resources -maxdepth 1 -type d -not -path './resources' -not -path './resources/3D_Shareware_v1.34' -not -path './resources/1.RV-Pre1' -printf '"%f", ' | sed -e 's/, $//' -e 's/15w14a/\0", "1.RV-Pre1", "3D_Shareware_v1.34/')
          echo "folders_json=[$FOLDERS]" >> $GITHUB_OUTPUT

  release:
    needs: [sync_and_prepare]
    if: needs.sync_and_prepare.outputs.has_commits == 'true'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        folder: ${{ fromJson(needs.sync_and_prepare.outputs.folders_json) }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Package Resources for ${{ matrix.folder }}
        id: package
        run: |
          cp sources/${{ matrix.folder }}/* resources/${{ matrix.folder }}/assets/minecraft/lang
          cd resources/${{ matrix.folder }}
          zip -r '../../[AFTP] ${{ matrix.folder }}.zip' ./*
          TIME="$(date +%y%m%d)" # Changed
          IS_NEWER=false
          if [[ '${{ needs.sync_and_prepare.outputs.recent_logs }}' =~ ${{ matrix.folder }} ]]; then
            IS_NEWER=true
          fi
          echo "time=$TIME" >> $GITHUB_OUTPUT
          echo "is_newer=$IS_NEWER" >> $GITHUB_OUTPUT

      - name: Upload to Modrinth
        if: steps.package.outputs.is_newer == 'true'
        uses: mc-wiki/modrinth-publish@main
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: '1NAoXRE0'
          version: '${{ inputs.name || steps.package.outputs.time }}+${{ matrix.folder }}'
          changelog: |
            ${{ inputs.changes && fromJson(inputs.changes) || '<!-- Add change notes here -->' }}

            Resource packs built from the latest Crowdin translations.
            - Run ID: ${{ github.run_id }}
            - Commit SHA: ${{ github.sha }}

            <details>
            <summary>Recent logs</summary>

            ${{ needs.sync_and_prepare.outputs.recent_logs }}
            </details>
          loaders: minecraft
          game-versions: ${{ matrix.folder == '3D_Shareware_v1.34' && '3D-Shareware-v1.34' || matrix.folder == '22w13oneBlockAtATime' && '22w13oneblockatatime' || matrix.folder }}
          files: '["[AFTP] ${{ matrix.folder }}.zip"]'
          channel: ${{ inputs.channel || needs.sync_and_prepare.outputs.channel }}
